In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")


class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )


    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits


model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 28, 28, device=device)
#print(X)
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

input_image = torch.rand(3, 28, 28)
print(input_image.size())

flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

layer1 = nn.Linear(in_features=28 * 28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)
print(logits)

print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")


Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
tensor([[ 0.0663,  0.0605,  0.0539, -0.0450,  0.0618,  0.0884, -0.0019, -0.0272,
         -0.0022,  0.0281]], grad_fn=<AddmmBackward0>)
Predicted class: tensor([5])
torch.Size([3, 28, 28])
torch.Size([3, 784])
torch.Size([3, 20])
Before ReLU: tensor([[ 0.4798,  0.3930,  0.0646,  0.2410, -0.5300,  0.1733,  0.9288,  0.1190,
         -0.1442,  0.4274,  0.1679, -0.5062,  0.1053, -0.3378,  0.2516, -0.4337,
          0.2108,  0.0485,  0.1998, -0.3547],
        [ 0.1239,  0.6986, -0.1665,  0.2992, -0.6248,  0.0093,  0.6635, -0.1841,
         -0.3447,  0.3648,  0.2900, -0.2041, -0.0400, -0.0994,  0.3502, -0.2625,
          0.0914, -0.2460,  0.6434, -0.0685],
     

In [1]:
import torch

a = [3, 4, 5]
b = a  # a and b refer to the same list object
print(f'{b}')
a[1] = 6
print(f'{b}')
for i in range(len(a)):
    a[i] += torch.randn(5, 3, requires_grad=False) if i % 3 else 1
print(f'{a}')
a[1] = 1
print(f'{b} {type(b)})')

[3, 4, 5]
[3, 6, 5]
[4, tensor([[7.6167, 5.0909, 5.2194],
        [6.4683, 5.1758, 6.8126],
        [6.1102, 5.2686, 6.0174],
        [7.6010, 6.3332, 6.6491],
        [4.8353, 5.8987, 6.5206]]), tensor([[4.9395, 3.9708, 4.9773],
        [3.9530, 4.3572, 5.5120],
        [5.7019, 4.8700, 4.2492],
        [4.2081, 6.7728, 4.5183],
        [4.7517, 5.1587, 3.0990]])]
[4, 1, tensor([[4.9395, 3.9708, 4.9773],
        [3.9530, 4.3572, 5.5120],
        [5.7019, 4.8700, 4.2492],
        [4.2081, 6.7728, 4.5183],
        [4.7517, 5.1587, 3.0990]])] <class 'list'>)


H:\deconf_TEMP\ipykernel_14232\1075045515.py:9: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xe (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  a[i] += torch.randn(5, 3, requires_grad=False) if i % 3 else 1


In [2]:
import requests
from lxml import html

page = requests.get('http://econpy.pythonanywhere.com/ex/001.html')
tree = html.fromstring(page.content)
#This will create a list of buyers:
buyers = tree.xpath('//div[@title="buyer-name"]/text()')
#This will create a list of prices
prices = tree.xpath('//span[@class="item-price"]/text()')

print('Buyers: ', buyers)
print('Prices: ', prices)

Buyers:  ['Carson Busses', 'Earl E. Byrd', 'Patty Cakes', 'Derri Anne Connecticut', 'Moe Dess', 'Leda Doggslife', 'Dan Druff', 'Al Fresco', 'Ido Hoe', 'Howie Kisses', 'Len Lease', 'Phil Meup', 'Ira Pent', 'Ben D. Rules', 'Ave Sectomy', 'Gary Shattire', 'Bobbi Soks', 'Sheila Takya', 'Rose Tattoo', 'Moe Tell']
Prices:  ['$29.95', '$8.37', '$15.26', '$19.25', '$19.25', '$13.99', '$31.57', '$8.49', '$14.47', '$15.86', '$11.11', '$15.98', '$16.27', '$7.50', '$50.85', '$14.26', '$5.68', '$15.00', '$114.07', '$10.09']


In [3]:
import records
import psycopg2
import time

db = records.Database('postgresql://wateradmin@kilitary.xyz:5432/wateradmin2')
items = db.query('select * from cart_items')  # or db.query_file('sqls/active-users.sql')
for item in items:
    print(f'{item}')
    time.sleep(0.9)

ModuleNotFoundError: No module named 'records'

In [4]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(f'w {w} b {b} z {z}')
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)


w tensor([[ 0.0529, -1.2535, -0.6065],
        [ 0.7778,  1.7929,  1.3373],
        [-0.5502, -1.4719, -1.3781],
        [ 1.6215,  0.3692, -1.0087],
        [ 0.3545, -2.0619, -0.0913]], requires_grad=True) b tensor([ 1.3144, -0.5872, -0.0697], requires_grad=True) z tensor([ 3.5708, -3.2124, -1.8170], grad_fn=<AddBackward0>)
Gradient function for z = <AddBackward0 object at 0x000001241CD67760>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001241CD65E40>
tensor([[0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466]])
tensor([0.3242, 0.0129, 0.0466])
