In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 28, 28, device=device)
#print(X)
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

input_image = torch.rand(3, 28, 28)
print(input_image.size())

flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

layer1 = nn.Linear(in_features=28 * 28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)
print(logits)

print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")


Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
tensor([[ 0.0811, -0.0861, -0.1692, -0.0368,  0.1309, -0.1530,  0.0359, -0.0251,
          0.0345,  0.0063]], grad_fn=<AddmmBackward0>)
Predicted class: tensor([4])
torch.Size([3, 28, 28])
torch.Size([3, 784])
torch.Size([3, 20])
Before ReLU: tensor([[-0.1114,  0.1655, -0.2328,  0.2356, -0.2080,  0.1848,  0.7391, -0.2523,
         -0.4909,  0.4529, -0.2896,  0.0791,  0.2361,  0.1119, -0.0032, -0.1394,
          0.3215,  0.0714, -0.6342,  0.2352],
        [-0.4608,  0.4634, -0.1448, -0.0537,  0.1184,  0.1252,  0.3527, -0.2643,
         -0.4075,  0.4259,  0.0252, -0.0348,  0.5428, -0.0508,  0.3134, -0.1955,
          0.5360, -0.1651, -0.3349,  0.2624],
     

In [7]:
import torch

a = [3, 4, 5]
b = a  # a and b refer to the same list object
print(f'{b}')
a[1] = 6
print(f'{b}')
for i in range(len(a)):
    a[i] += torch.randn(5, 3, requires_grad=False) if i % 3 else 1
print(f'{a}')
a[1] = 1
print(f'{b} {type(b)})')

a = 4
b = a // 2
print(b)

[3, 4, 5]
[3, 6, 5]
[4, tensor([[6.2407, 4.3074, 6.6834],
        [6.2378, 5.3191, 7.7576],
        [6.1277, 6.4511, 6.4315],
        [7.3500, 6.7342, 4.6958],
        [6.6259, 6.1049, 4.8670]]), tensor([[4.2752, 6.3827, 4.9688],
        [4.0993, 5.7190, 8.5414],
        [4.7677, 5.6207, 6.5143],
        [5.6958, 4.6735, 6.8876],
        [4.1779, 3.8175, 5.0746]])]
[4, 1, tensor([[4.2752, 6.3827, 4.9688],
        [4.0993, 5.7190, 8.5414],
        [4.7677, 5.6207, 6.5143],
        [5.6958, 4.6735, 6.8876],
        [4.1779, 3.8175, 5.0746]])] <class 'list'>)
2


In [4]:
import requests
from lxml import html
import pprint

pp = pprint.PrettyPrinter(indent=4)

page = requests.get('http://econpy.pythonanywhere.com/ex/001.html')
pprint.pprint(page.content)
tree = html.fromstring(page.content)
#This will create a list of buyers:
buyers = tree.xpath('//div[@title="buyer-name"]/text()')
#This will create a list of prices
prices = tree.xpath('//span[@class="item-price"]/text()')

print('Buyers: ', buyers)
print('Prices: ', prices)

(b'\n<html>\n    <head>\n        <title>Something went wrong :-(</title>\n     '
 b'   <link href="https://www.pythonanywhere.com/static/bootstrap/css/bootstrap'
 b'.css" rel="stylesheet" media="screen" type="text/css">\n        <style>\n '
 b'           body {\n                font-family: Helvetica, Arial, sans-se'
 b'rif;\n                width: 500px;\n                margin-left: auto;\n  '
 b'              margin-right: auto;\n                margin-top: 20px;\n    '
 b'        }\n\n            iframe {\n                width: 100%;\n           '
 b'     height: 100%;\n                border: none;\n            }\n        <'
 b'/style>\n    </head>\n\n    <body>\n        <div class="main">\n        <'
 b'div class="banner">\n            <h1>Something went wrong :-(</h1>\n\n     '
 b'       <p>\n            Something went wrong while trying to load this we'
 b'bsite;\n            please try again later.\n            </p>\n\n           '
 b' <p>\n            If it is your site, you

In [3]:
import records
import psycopg2
import time

db = records.Database('postgresql://wateradmin@kilitary.xyz:5432/wateradmin2')
items = db.query('select * from cart_items')  # or db.query_file('sqls/active-users.sql')
for item in items:
    print(f'{item}')
    time.sleep(0.9)

ModuleNotFoundError: No module named 'records'

In [9]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(f'w {w} b {b} z {z}')
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)


w tensor([[-0.6661, -2.1577,  0.7268],
        [ 0.2644, -0.1757,  0.0706],
        [-0.7501, -1.8445, -1.3773],
        [ 1.8543, -0.9306, -1.2281],
        [ 1.7637, -0.6242,  0.0769]], requires_grad=True) b tensor([1.4208, 0.2189, 1.6642], requires_grad=True) z tensor([ 3.8870, -5.5139, -0.0668], grad_fn=<AddBackward0>)
Gradient function for z = <AddBackward0 object at 0x00000294742B7D00>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x0000029473F56DC0>
tensor([[0.3266, 0.0013, 0.1611],
        [0.3266, 0.0013, 0.1611],
        [0.3266, 0.0013, 0.1611],
        [0.3266, 0.0013, 0.1611],
        [0.3266, 0.0013, 0.1611]])
tensor([0.3266, 0.0013, 0.1611])
