In [1]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms


device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

class NeuralNetwork(nn.Module):

    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28 * 28, 512),
            nn.ReLU(),
            nn.Linear(512, 512),
            nn.ReLU(),
            nn.Linear(512, 10),
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 28, 28, device=device)
#print(X)
logits = model(X)
print(logits)
pred_probab = nn.Softmax(dim=1)(logits)
y_pred = pred_probab.argmax(1)
print(f"Predicted class: {y_pred}")

input_image = torch.rand(3, 28, 28)
print(input_image.size())

flatten = nn.Flatten()
flat_image = flatten(input_image)
print(flat_image.size())

layer1 = nn.Linear(in_features=28 * 28, out_features=20)
hidden1 = layer1(flat_image)
print(hidden1.size())

print(f"Before ReLU: {hidden1}\n\n")
hidden1 = nn.ReLU()(hidden1)
print(f"After ReLU: {hidden1}")

seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20, 10)
)
input_image = torch.rand(3, 28, 28)
logits = seq_modules(input_image)
print(logits)

print(f"Model structure: {model}\n\n")

for name, param in model.named_parameters():
    print(f"Layer: {name} | Size: {param.size()} | Values : {param[:2]} \n")


Using cpu device
NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
tensor([[-0.0551,  0.0902,  0.1109, -0.0778, -0.1523, -0.0747, -0.0842,  0.0629,
         -0.0452,  0.0109]], grad_fn=<AddmmBackward0>)
Predicted class: tensor([2])
torch.Size([3, 28, 28])
torch.Size([3, 784])
torch.Size([3, 20])
Before ReLU: tensor([[-1.4302e-01,  9.6974e-02,  3.4681e-02, -1.5573e-01, -7.3948e-01,
         -1.8961e-01, -8.1212e-01,  4.6736e-01,  9.1681e-01,  5.3387e-03,
         -3.9114e-01, -4.4701e-01,  2.2905e-02,  1.8201e-01, -2.1667e-04,
         -5.2165e-01, -2.0063e-01, -2.4497e-01, -1.0486e-01,  9.0448e-02],
        [-3.8301e-01, -8.3009e-02, -1.2984e-01, -2.6811e-01, -4.3271e-01,
          6.0974e-02, -7.7093e-01,  3.8469e-01,  3

In [13]:
import torch


a = [3, 4, 5]
b = a  # a and b refer to the same list object
print(f'{b}')
a[1] = 6
print(f'{b}')
for i in range(len(a)):
    a[i] += torch.randn(5, 3, requires_grad=False) if i % 3 else 1
print(f'{a}')
a[1] = 1
print(f'{b} {type(b)})')

a=4
b=a//2
print(b)

[3, 4, 5]
[3, 6, 5]
[4, tensor([[6.6687, 5.4601, 5.2171],
        [6.6477, 5.7554, 6.9142],
        [5.9767, 6.5670, 7.0807],
        [7.8632, 5.4008, 6.5975],
        [6.5069, 5.9347, 7.3944]]), tensor([[3.8375, 4.9677, 4.7583],
        [7.7648, 5.1790, 5.6567],
        [5.4881, 5.3841, 6.2662],
        [5.6773, 3.1149, 5.9589],
        [3.9986, 4.2413, 5.3670]])]
[4, 1, tensor([[3.8375, 4.9677, 4.7583],
        [7.7648, 5.1790, 5.6567],
        [5.4881, 5.3841, 6.2662],
        [5.6773, 3.1149, 5.9589],
        [3.9986, 4.2413, 5.3670]])] <class 'list'>)
2


In [2]:
import requests
from lxml import html


page = requests.get('http://econpy.pythonanywhere.com/ex/001.html')
tree = html.fromstring(page.content)
#This will create a list of buyers:
buyers = tree.xpath('//div[@title="buyer-name"]/text()')
#This will create a list of prices
prices = tree.xpath('//span[@class="item-price"]/text()')

print('Buyers: ', buyers)
print('Prices: ', prices)

Buyers:  ['Carson Busses', 'Earl E. Byrd', 'Patty Cakes', 'Derri Anne Connecticut', 'Moe Dess', 'Leda Doggslife', 'Dan Druff', 'Al Fresco', 'Ido Hoe', 'Howie Kisses', 'Len Lease', 'Phil Meup', 'Ira Pent', 'Ben D. Rules', 'Ave Sectomy', 'Gary Shattire', 'Bobbi Soks', 'Sheila Takya', 'Rose Tattoo', 'Moe Tell']
Prices:  ['$29.95', '$8.37', '$15.26', '$19.25', '$19.25', '$13.99', '$31.57', '$8.49', '$14.47', '$15.86', '$11.11', '$15.98', '$16.27', '$7.50', '$50.85', '$14.26', '$5.68', '$15.00', '$114.07', '$10.09']


In [3]:
import records
import psycopg2
import time


db = records.Database('postgresql://wateradmin@kilitary.xyz:5432/wateradmin2')
items = db.query('select * from cart_items')  # or db.query_file('sqls/active-users.sql')
for item in items:
    print(f'{item}')
    time.sleep(0.9)

ModuleNotFoundError: No module named 'records'

In [4]:
x = torch.ones(5)  # input tensor
y = torch.zeros(3)  # expected output
w = torch.randn(5, 3, requires_grad=True)
b = torch.randn(3, requires_grad=True)
z = torch.matmul(x, w) + b
loss = torch.nn.functional.binary_cross_entropy_with_logits(z, y)
print(f'w {w} b {b} z {z}')
print(f"Gradient function for z = {z.grad_fn}")
print(f"Gradient function for loss = {loss.grad_fn}")

loss.backward(retain_graph=True)
print(w.grad)
print(b.grad)


w tensor([[ 0.0529, -1.2535, -0.6065],
        [ 0.7778,  1.7929,  1.3373],
        [-0.5502, -1.4719, -1.3781],
        [ 1.6215,  0.3692, -1.0087],
        [ 0.3545, -2.0619, -0.0913]], requires_grad=True) b tensor([ 1.3144, -0.5872, -0.0697], requires_grad=True) z tensor([ 3.5708, -3.2124, -1.8170], grad_fn=<AddBackward0>)
Gradient function for z = <AddBackward0 object at 0x000001241CD67760>
Gradient function for loss = <BinaryCrossEntropyWithLogitsBackward0 object at 0x000001241CD65E40>
tensor([[0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466],
        [0.3242, 0.0129, 0.0466]])
tensor([0.3242, 0.0129, 0.0466])
